In [ ]:
import numpy as np
#from numpy import array
#from numpy import arange

In [ ]:
a = np.array([1,2,5,3,6,6,7])
a

array([1, 2, 5, 3, 6, 6, 7])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(7,)

In [ ]:
a = np.array([[1,2,5,4,7,8], [5,4,8,9,6,3]])
a

array([[1, 2, 5, 4, 7, 8],
       [5, 4, 8, 9, 6, 3]])

In [ ]:
a.shape

(2, 6)

In [ ]:
a = np.array([[[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]]])
a

array([[[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]]])

In [ ]:
a.shape

(4, 2, 6)

In [ ]:
a = np.array([[[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]],
           [[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]],
              [[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]]])
a

array([[[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]],


       [[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]],


       [[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]]])

In [ ]:
#3 times an array structure having 4 arrays that contain 2 rows & 5 columns
a.shape

(3, 4, 2, 5)

In [ ]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a = np.arange(5, 50)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a = np.arange(5, 50, 3)
a

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
a = np.arange(24).reshape((6,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a = np.arange(26).reshape((6,4))
a

ValueError: cannot reshape array of size 26 into shape (6,4)

In [ ]:
x = np.random.randint(1,10, 25)
x

array([8, 6, 1, 9, 4, 2, 5, 5, 6, 1, 1, 7, 1, 9, 5, 6, 3, 7, 2, 9, 4, 9,
       5, 3, 8])

In [ ]:
x = np.random.randn()
x

1.0455465492532146

In [ ]:
x = np.random.randn(5)
x

array([ 1.28062703, -0.78731289,  0.75355431,  0.43572424,  2.40525906])

In [ ]:
x = np.random.random(10)
x

array([0.36800062, 0.33772144, 0.28050291, 0.85092514, 0.48225045,
       0.52672566, 0.55783935, 0.11442001, 0.51368579, 0.57111594])

In [ ]:
x= np.random.choice(100,50,replace=False)
x

array([57, 55, 59, 88, 86, 43, 60, 32, 50,  3, 87, 62, 34, 85, 14, 68,  8,
       36,  9, 27, 99, 97, 95, 49, 39, 63, 70, 46, 96, 25,  1, 83, 78, 81,
       84, 79, 54, 37, 71, 41, 40, 74, 75, 17, 45, 90, 58, 31, 73, 30])

In [ ]:
x = np.linspace(2,9,7)
x

array([2.        , 3.16666667, 4.33333333, 5.5       , 6.66666667,
       7.83333333, 9.        ])

In [ ]:
for i in range(len(x)-1):
  print(i)
  print('Difference between index',i+1,'&',i,'is',x[i+1] - x[i])
x[2] - x[1]

0
Difference between index 1 & 0 is 1.166666666666667
1
Difference between index 2 & 1 is 1.166666666666667
2
Difference between index 3 & 2 is 1.166666666666666
3
Difference between index 4 & 3 is 1.166666666666667
4
Difference between index 5 & 4 is 1.166666666666667
5
Difference between index 6 & 5 is 1.166666666666666


1.166666666666667

In [ ]:
x = np.linspace(3,9,9)
x

array([3.  , 3.75, 4.5 , 5.25, 6.  , 6.75, 7.5 , 8.25, 9.  ])

In [ ]:
for i in range(len(x)-1):
  print(i)
  print('Difference between index',i+1,'&',i,'is',x[i+1] - x[i])

0
Difference between index 1 & 0 is 0.75
1
Difference between index 2 & 1 is 0.75
2
Difference between index 3 & 2 is 0.75
3
Difference between index 4 & 3 is 0.75
4
Difference between index 5 & 4 is 0.75
5
Difference between index 6 & 5 is 0.75
6
Difference between index 7 & 6 is 0.75
7
Difference between index 8 & 7 is 0.75


In [ ]:
a = np.random.randint(0,9,21).reshape((3,7))
a

array([[3, 6, 8, 7, 8, 8, 0],
       [0, 5, 6, 1, 4, 7, 8],
       [8, 4, 8, 2, 6, 4, 6]])

In [ ]:
#Columnwise summation
print(a)
a.sum(axis=0)

[[3 6 8 7 8 8 0]
 [0 5 6 1 4 7 8]
 [8 4 8 2 6 4 6]]


array([11, 15, 22, 10, 18, 19, 14])

In [ ]:
#Columnwise summation
print(a)
a.sum(axis=1)

[[3 6 8 7 8 8 0]
 [0 5 6 1 4 7 8]
 [8 4 8 2 6 4 6]]


array([40, 31, 38])

In [ ]:
print(a)
print(a.mean(axis=0))
print(a.mean(axis=1))

[[3 6 8 7 8 8 0]
 [0 5 6 1 4 7 8]
 [8 4 8 2 6 4 6]]
[3.66666667 5.         7.33333333 3.33333333 6.         6.33333333
 4.66666667]
[5.71428571 4.42857143 5.42857143]


In [ ]:
print(a)
print(a.min(axis=0))
print(a.min(axis=1))

[[3 6 8 7 8 8 0]
 [0 5 6 1 4 7 8]
 [8 4 8 2 6 4 6]]
[0 4 6 1 4 4 0]
[0 0 2]


In [ ]:
print(a)
print(a.max(axis=0))
print(a.max(axis=1))

[[3 6 8 7 8 8 0]
 [0 5 6 1 4 7 8]
 [8 4 8 2 6 4 6]]
[8 6 8 7 8 8 8]
[8 8 8]


In [ ]:
#Cummulative Summation
a = np.random.randint(0,9,21)
print(a)
np.cumsum(a)

[1 4 3 8 1 6 1 3 5 3 8 6 3 4 2 1 1 7 3 7 5]


array([ 1,  5,  8, 16, 17, 23, 24, 27, 32, 35, 43, 49, 52, 56, 58, 59, 60,
       67, 70, 77, 82])

In [ ]:
a = np.random.randint(0,9,28).reshape((4,7))
print(a)
np.square(a)

[[0 2 3 5 1 5 0]
 [7 0 0 7 7 2 5]
 [8 4 1 8 7 2 7]
 [3 7 7 1 2 6 6]]


array([[ 0,  4,  9, 25,  1, 25,  0],
       [49,  0,  0, 49, 49,  4, 25],
       [64, 16,  1, 64, 49,  4, 49],
       [ 9, 49, 49,  1,  4, 36, 36]])

In [ ]:
a = np.random.randint(1,9,28).reshape((4,7))
print(a)
np.sqrt(a)

[[4 1 5 5 1 4 5]
 [5 8 3 6 2 6 6]
 [2 4 8 7 7 5 7]
 [7 5 1 2 4 3 3]]


array([[2.        , 1.        , 2.23606798, 2.23606798, 1.        ,
        2.        , 2.23606798],
       [2.23606798, 2.82842712, 1.73205081, 2.44948974, 1.41421356,
        2.44948974, 2.44948974],
       [1.41421356, 2.        , 2.82842712, 2.64575131, 2.64575131,
        2.23606798, 2.64575131],
       [2.64575131, 2.23606798, 1.        , 1.41421356, 2.        ,
        1.73205081, 1.73205081]])

In [ ]:
#Horizontal Stack
a = np.random.randint(1,9,28).reshape((4,7))
print(a)
b = np.random.randint(1,9,20).reshape((4,5))
print(b)
np.hstack((a,b))

[[3 1 7 3 7 6 6]
 [4 6 8 2 7 3 4]
 [5 7 5 2 1 2 1]
 [2 4 1 3 8 3 1]]
[[1 7 4 6 5]
 [1 7 4 5 4]
 [1 7 4 5 4]
 [3 1 4 1 2]]


array([[3, 1, 7, 3, 7, 6, 6, 1, 7, 4, 6, 5],
       [4, 6, 8, 2, 7, 3, 4, 1, 7, 4, 5, 4],
       [5, 7, 5, 2, 1, 2, 1, 1, 7, 4, 5, 4],
       [2, 4, 1, 3, 8, 3, 1, 3, 1, 4, 1, 2]])

In [ ]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 5

In [ ]:
#Vertical Stack
a = np.random.randint(1,9,30).reshape((5,6))
print(a)
b = np.random.randint(1,9,24).reshape((4,6))
print(b)
np.vstack((a,b))

[[4 2 5 8 3 7]
 [6 3 1 3 6 1]
 [3 8 7 4 1 1]
 [2 6 3 5 2 3]
 [6 3 4 3 1 6]]
[[3 6 2 6 1 2]
 [3 4 4 5 3 3]
 [6 8 1 7 2 8]
 [5 3 2 6 6 5]]


array([[4, 2, 5, 8, 3, 7],
       [6, 3, 1, 3, 6, 1],
       [3, 8, 7, 4, 1, 1],
       [2, 6, 3, 5, 2, 3],
       [6, 3, 4, 3, 1, 6],
       [3, 6, 2, 6, 1, 2],
       [3, 4, 4, 5, 3, 3],
       [6, 8, 1, 7, 2, 8],
       [5, 3, 2, 6, 6, 5]])

In [ ]:
a = np.random.randint(1,9,12).reshape((3,4))
print(a)
b = np.random.randint(1,9,12).reshape((3,4))
print(b)

[[5 2 2 2]
 [1 7 1 5]
 [2 5 5 7]]
[[8 4 8 3]
 [1 4 3 7]
 [7 4 2 7]]


In [ ]:
print(a)
print(b)
a+b

[[5 2 2 2]
 [1 7 1 5]
 [2 5 5 7]]
[[8 4 8 3]
 [1 4 3 7]
 [7 4 2 7]]


array([[13,  6, 10,  5],
       [ 2, 11,  4, 12],
       [ 9,  9,  7, 14]])

In [ ]:
print(a)
print(b)
a*b

[[5 2 2 2]
 [1 7 1 5]
 [2 5 5 7]]
[[8 4 8 3]
 [1 4 3 7]
 [7 4 2 7]]


array([[40,  8, 16,  6],
       [ 1, 28,  3, 35],
       [14, 20, 10, 49]])

In [ ]:
np.dot(a,b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
a = np.random.randint(1,9,12).reshape((3,4))
print(a)
b = np.random.randint(1,9,16).reshape((4,4))
print(b)

[[2 1 7 5]
 [2 8 8 5]
 [7 3 4 3]]
[[7 8 3 8]
 [4 6 4 5]
 [4 4 5 6]
 [2 3 5 3]]


In [ ]:
#mat1(3,4) * mat2(4,4) = result(3*4)

#result[0,0] = 2*7 + 1*4 + 7*4 + 5*2 = 56
#result[0,1] = 2*8 + 1*6 + 7*4 + 5*3 = 65
#result[0,2] = 2*3 + 1*4 + 7*5 + 5*5 = 70
#result[1,0] = 2*7 + 8*4 + 8*4 + 5*2 = 88

np.dot(a,b)

array([[ 56,  65,  70,  78],
       [ 88, 111, 103, 119],
       [ 83,  99,  68, 104]])