### DATA ANALYSIS:
-IT IS MAINLY USED FOR DATA CLEANING AND MANIPULATION,DATA ORGANIZING THE DATA.
### LIBRARIES
1.NUMPY
2.PANDAS
3.MATLOTLIB
4.SEABORN

# NUMPY
-NUMPY STANDS FOR NUMERICAL PYTHON.
-IT IS MAINLY USED FOR N-DIMENTIONAL ARRAYS
-HOW TO CREATE NUMPY:
  LIST,TUPLE,DICTIONARY,RANGE,ARANGE,RANDOM.
-FIRST WE NEED TO IMPORT NUMPY LIBRARY.
-UISNG IMPORT KEYWORD
    IMPORT NUMPY AS NP

In [2]:
#IMPORT NUMPY LIBRARY....
import numpy as np 

In [5]:
#To get the currnt version of numpy array
np.__version__

'1.21.5'

In [4]:
#to create numpy 1-d array using list?
n1=np.array([10,20,30,40])
print(n1)
print(type(n1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [3]:
a=np.array(['nanda','jashu','siva','eswar','naresh'])
print(a)
print(type(a))

['nanda' 'jashu' 'siva' 'eswar' 'naresh']
<class 'numpy.ndarray'>


In [5]:
# to create 2-d numpy array using list?
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(b)
print(type(b))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>


In [7]:
# to create numpy arrray using tuple?
n1=np.array((10,20,30,40))
print(n1)
print(type(n1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# to create numpy arrray using dictionary?
n1=np.array({"name":"naresh","rollno":516,"branch":"cse"})
print(n1)
print(type(n1))

{'name': 'naresh', 'rollno': 516, 'branch': 'cse'}
<class 'numpy.ndarray'>


In [11]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_row)
print(vector_column)
print(type(vector_row))
print(type(vector_column))

[1 2 3]
[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
# Create a matrix
matrix = np.array([[1, 2, 3],
                   [1, 2, 4],
                   [1, 2, 5]])
print(matrix)
print(type(matrix))

[[1 2 3]
 [1 2 4]
 [1 2 5]]
<class 'numpy.ndarray'>


In [22]:
# To create numpy arrray using range?
c=np.array(range(10,100))
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [23]:
# to create numpy arrray using arange?
d=np.arange(100)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [26]:
# generate an array of 5 random numbers
array1 = np.random.rand(5)
print(array1)

[0.04871    0.82207153 0.27627313 0.06681387 0.75934225]


In [29]:
# generate an array of 5 random numbers
array1 = np.random.randint(5)
print(array1)

2


In [30]:
# create an array with 4 elements filled with zeros
array2 = np.zeros(10)
print(array2)
# Output: [0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)
# Output: [2  4  6 8]

[2 4 6 8]


In [31]:
# create an array with 4 elements filled with ones
array2 = np.ones(10)
print(array2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [32]:
# create an array with 4 elements filled with zeros
array3 = np.twos(4)
print(array3)

AttributeError: module 'numpy' has no attribute 'twos'

In [33]:
import numpy as np
# create an empty array of length 4
array4 = np.empty(4)

print(array4)

[0. 0. 0. 0.]


In [34]:
# create a 2D array with 2 rows and 4 columns
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array5 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8], 
                [9, 10, 11, 12]],
                     
                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

print(array5)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# To create multidimensional arrays from scratch we use functions such as
# np.zeros()
# np.arange()
# np.random.rand()

In [45]:
# create 2D array with 2 rows and 3 columns filled with zeros
array6 = np.zeros([2, 3])

print("2-D Array: ")
print(array6)

# create 3D array with dimensions 2x3x4 filled with zeros
array7 = np.zeros((2, 3, 4))

print("\n3-D Array: ")
print(array7)

2-D Array: 
[[0. 0. 0.]
 [0. 0. 0.]]

3-D Array: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [36]:
# create 2D array with 2 rows and 3 columns filled with ones
array8 = np.ones((2, 3))

print("2-D Array: ")
print(array8)

# create 3D array with dimensions 2x3x4 filled with ones
array9 = np.ones((2, 3, 4))

print("\n3-D Array: ")
print(array9)

2-D Array: 
[[1. 1. 1.]
 [1. 1. 1.]]

3-D Array: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [37]:
# In NumPy, we can use the np.full() function to
# create a multidimensional array with a specified value.

# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((10, 10), 100)

print("Array:", numpy_array)

Array: [[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [38]:
# create a 2D array of 2 rows and 2 columns of random numbers
array = np.random.rand(2, 2)
print("2-D Array: ")
print(array)
# create a 3D array of shape (2, 2, 2) of random numbers
array = np.random.rand(2, 2, 2)
print("\n3-D Array: ")
print(array)

2-D Array: 
[[0.51358693 0.92345815]
 [0.93035259 0.62280651]]

3-D Array: 
[[[0.67046653 0.47247117]
  [0.49766447 0.73175757]]

 [[0.11128673 0.22419879]
  [0.80609359 0.99558486]]]


In [39]:
import numpy as np

# create an empty 2D array with 2 rows and 2 columns
array1 = np.empty((2, 2))

print("2-D Array: ")
print(array1)

# create an empty 3D array of shape (2, 2, 2) 
array2 = np.empty((2, 2, 2))

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0.51358693 0.92345815]
 [0.93035259 0.62280651]]

3-D Array: 
[[[0.67046653 0.47247117]
  [0.49766447 0.73175757]]

 [[0.11128673 0.22419879]
  [0.80609359 0.99558486]]]


# NumPy Data Types
NumPy offers a wider range of numerical data types than what is available in Python. 
Here's the list of most commonly used numeric data types in NumPy:
                                                    
-->int8, int16, int32, int64 - signed integer types with different bit sizes
-->uint8, uint16, uint32, uint64 - unsigned integer types with different bit sizes
-->float32, float64 - floating-point types with different precision levels
-->complex64, complex128 - complex number types with different precision levels

In [40]:
# Check Data Type of a NumPy Array
# To check the data type of a NumPy array, we can use the dtype attribute. For example,
import numpy as np

# create an array of integers 
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype) 

# Output: int64

int64


In [49]:
import numpy as np

# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)  # prints int64

# check the data type of float_array
print(float_array.dtype)  # prints float64

# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

int32
float64
complex128


In [42]:
# Creating NumPy Arrays With a Defined Data Type
# In NumPy, we can create an array with a defined data type by passing the dtype parameter while calling the np.array() function. For example,

import numpy as np

# create an array of 32-bit integers
array1 = np.array([1, 3, 7], dtype='int32')

print(array1, array1.dtype)

[1 3 7] int32


In [43]:
# Example: Creating NumPy Arrays With a Defined Data Type
# import numpy as np

# create an array of 8-bit integers
array1 = np.array([1, 3, 7], dtype='int8')

# create an array of unsigned 16-bit integers
array2 = np.array([2, 4, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')

# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


In [44]:
# NumPy Type Conversion
# In NumPy, we can convert the data type of an array using the astype() method. For example,

# import numpy as np

# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype('float')

# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


# attributes of numpy array:
<!-- NumPy Array Attributes
In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

For example, to get the dimension of an array, we can use the ndim attribute. -->
-shape
-dtype
-ndim
-size
Attributes	Description
ndim	returns number of dimension of the array
size	returns number of elements in the array
dtype	returns data type of elements in the array
shape	returns the size of the array in each dimension.
itemsize	returns the size (in bytes) of each elements in the array
data	returns the buffer containing actual elements of the array in memory

In [46]:
# create a 2-D array 
array1 = np.array([[2, 4, 6],
                  [1, 3, 5]])

# check the dimension of array1
print(array1.ndim) 

# Output: 2

2


In [47]:
array1 = np.array([[1, 2, 3],
                 [6, 7, 8]])

# return total number of elements in array1
print(array1.size)

# Output: 6

6


In [56]:
# NumPy Array shape Attribute
# In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension. For example,

# import numpy as np

array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

# Output: (2,3)

(2, 3)


In [57]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

# Output: (2,3)

(2, 3)


In [62]:
# NumPy Array itemsize Attribute
# In NumPy, the itemsize attribute determines size (in bytes) of each element in the array. For example,

# import numpy as np

# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13,23,45,67,89,65,43],dtype=np.int64)

# create a 1-D array of 32-bit integers 
array2 = np.array([6, 7, 8, 10, 13,34,567,765,34], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)  # prints 8
print(array2.itemsize)  # prints 4

8
4


In [63]:
# NumPy Array data Attribute
# In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

# In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

# Let's see an example.
import numpy as np

array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x000001CB81ADDE80>
Data of array2 is:  <memory at 0x000001CB81AE3930>


In [8]:
n1=np.array([[1,2,3],[4,5,6]])
print(n1)
print(n1.shape)
print(n1.ndim)
print(n1.size)
print(n1.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32


In [ ]:
# NumPy Input Output
# NumPy offers input/output (I/O) functions for loading and saving data to and from files.
# Input/output functions support a variety of file formats, including binary and text formats.
# The binary format is designed for efficient storage and retrieval of large arrays.
# The text format is more human-readable and can be easily edited in a text editor.
Most Commonly Used I/O Functions
Here are some of the commonly used NumPy Input/Output functions:

Function	Description
save()	saves an array to a binary file in the NumPy .npy format.
load()	loads data from a binary file in the NumPy .npy format
savetxt()	saves an array to a text file in a specific format
loadtxt()	loads data from a text file.

In [48]:
# NumPy save() Function
# In NumPy, the save() function is used to save an array to a binary file in the NumPy .npy format.
# Here's the syntax of the save() function,
# np.save(file, array)
# file - specifies the file name (along with path if required)
# array - specifies the NumPy array to be saved
# Now, let's see an example.
# import numpy as np
# create a NumPy array
array1 = np.array([[1, 3, 5], 
                   [7, 9, 11]])
# save the array to a file
np.save('file1.npy', array1)

In [49]:
# NumPy load() Function
# In the previous example, we saved an array to a binary file. Now we'll load that saved file using the load() function.
# Let's see an example.
# import numpy as np
# load the saved NumPy array
loaded_array = np.load('file1.npy')

# display the loaded array
print(loaded_array)

[[ 1  3  5]
 [ 7  9 11]]


In [66]:
# NumPy savetxt() Function
# In NumPy, we use the savetxt() function to save an array to a text file.

# Here's the syntax of the savetxt() function:

# np.save(file, array)
# file - specifies the file name
# array - specifies the NumPy array to be saved
# Now, let's see an example,
# import numpy as np
# create a NumPy array
array2 = np.array([[1, 3, 5], 
                   [7, 9, 11]])

# save the array to a file
np.savetxt('file2.txt', array2)

In [67]:
# NumPy loadtxt() Function
# We use the loadtxt() function to load the saved txt file.
# Let's see an example to load the file2.txt file that we saved earlier.
# import numpy as np
# load the saved NumPy array
loaded_array = np.loadtxt('file2.txt')

# display the loaded array
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


Numpy Array Indexing
In NumPy, each element in an array is associated with a number. The number is known as an array index.
Let's see an example to demonstrate NumPy array indexing.
Array Index in NumPy 
Array Indexing in NumPy
In the above array, 5 is the 3rd element. However, its index is 2.
This is because the array indexing starts from 0, that is, the first element of the array has index 0, the second element has index 1, and so on.
Now, we'll see how we can access individual items from the array using the index number.
Access Array Elements Using Index
We can use indices to access individual elements of a NumPy array.
Suppose we have a NumPy array:
array1 = np.array([1, 3, 5, 7, 9])
Now, we can use the index number to access array elements as:
array1[0] - to access the first element, i.e. 1
array1[2] - to access the third element, i.e. 5
array1[4] - to access the fifth element, i.e. 9

In [68]:
# Example: Access Array Elements Using Index
# import numpy as np

array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])    # prints 1
print(array1[2])    # prints 5
print(array1[4])    # prints 9

1
5
9


In [69]:
# Modify Array Elements Using Index
# We can use indices to change the value of an element 
# in a NumPy array. For example,
# import numpy as np
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)    # prints [12 4 6 8 10]

# change the value of the third element
numbers[2] = 14
print("After modifying third element:",numbers)    # prints [12 4 14 8 10]

After modifying first element: [12  4  6  8 10]
After modifying third element: [12  4 14  8 10]


In [70]:
# NumPy Negative Array Indexing
# NumPy allows negative indexing for its array. The index of -1 refers to the last item, -2 to the second last item and so on.

# NumPy Array Negative Indexing
# NumPy Array Negative Indexing
# Let's see an example.

# import numpy as np

# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7

9
7


In [72]:
# Modify Array Elements Using Negative Indexing

# Similar to regular indexing, we can also modify array elements using negative indexing. For example,

# import numpy as np

# create a numpy array
numbers = np.array([2, 3, 5, 7, 11])

# modify the last element
numbers[-1] = 13
print(numbers)    # Output: [2 3 5 7 13]

# modify the second-to-last element
numbers[-2] = 17
print(numbers)    # Output: [2 3 5 17 13]

[ 2  3  5  7 13]
[ 2  3  5 17 13]


2-D NumPy Array Indexing
Array indexing in NumPy allows us to access and manipulate elements in a 2-D array.

To access an element of array1, we need to specify the row index and column index of the element. Suppose we have following 2-D array,

array1 = np.array([[1, 3, 5], 
                     [7, 9, 2], 
                     [4, 6, 8]])
Now, say we want to access the element in the third row and second column we specify the index as:

array1[2, 1] # returns 6
Since we know indexing starts from 0. So to access the element in the third row and second column, we need to use index 2 for the third row and index 1 for the second column respectively.

In [5]:
# import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)  

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)  

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [6]:
# Access Row or Column of 2D Array Using Indexing
# In NumPy, we can access specific rows or columns of a 2-D array using array indexing.

# Let's see an example.

# import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5], 
             [7, 9, 2], 
             [4, 6, 8]])

# access the second row of the array
second_row = array1[1, :]
print("Second Row:", second_row)  # Output: [7 9 2]

# access the third column of the array
third_col = array1[:, 2]
print("Third Column:", third_col)  # Output: [5 2 8]

Second Row: [7 9 2]
Third Column: [5 2 8]


3-D NumPy Array Indexing
We learned how to access elements in a 2D array. We can also access elements in higher dimensional arrays.

To access an element of a 3D array, we use three indices separated by commas.

The first index refers to the slice
The second index refers to the row
The third index refers to the column.
Note: In 3D arrays, slice is a 2D array that is obtained by taking a subset of the elements in one of the dimensions.

In [7]:
import numpy as np

# create a 3D array with shape (2, 3, 4)
array1 = np.array([[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                     
                    [[13, 14, 15, 16], 
                    [17, 18, 19, 20], 
                    [21, 22, 23, 24]]])

# access a specific element of the array
element = array1[1, 2, 1]

# print the value of the element
print(element) 
 
# Output: 22
# Here, we created a 3D array called array1 with shape (2, 3, 4). This array contains 2 2D arrays, each with 3 rows and 4 columns.

# Then, we used indexing to access a specific element of array1. Notice the code,

# array1[1, 2, 1]
# Here,

# array1[1, , ,] - access the second 2D array, i.e.
# [13, 14, 15, 16], 
# [17, 18, 19, 20], 
# [21, 22, 23, 24]
# array1[ ,2, ] - access the third row of the 2D array, i.e.
# [21, 22, 23, 24]
# array1[ , ,1] - access the second element of the third row, i.e.


22


NumPy Array Slicing
Array Slicing is the process of extracting a portion of an array.

With slicing, we can easily access elements in the array. It can be done on one or more dimensions of a NumPy array.

Syntax of NumPy Array Slicing
Here's the syntax of array slicing in NumPy:

array[start:stop:step]
Here,

start - index of the first element to be included in the slice
stop - index of the last element (exclusive)
step - step size between each element in the slice
Note: When we slice arrays, the start index is inclusive but the stop index is exclusive.

If we omit start, slicing starts from the first element
If we omit stop, slicing continues up to the last element
If we omit step, default step size is 1


In [8]:
import numpy as np

# create a 1D array 
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]
# In the above example, we have created the array named array1 with 9 elements.

# Then, we used the slicing operator : to slice array elements.

# array1[2:6] - slices array1 from index 2 to index 6, not including index 6
# array1[0:8:2] - slices array1 from index 0 to index 8, not including index 8
# array1[3:] - slices array1 from index 3 up to the last element
# array1[:] - returns all items from beginning to end


[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


Modify Array Elements Using Slicing
With slicing, we can also modify array elements using:

start parameter
stop parameter
start and stop parameter
start, stop, and step parameter

In [50]:
# 1. Using start Parameter
# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)

# Output: [ 2  4  6 20 20 20]


[ 2  4  6 20 20 20]


In [51]:
# 2. Using stop Parameter
# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify the first 3 elements
numbers[:3] = 40
print(numbers)

# Output: [40 40 40  8 10 12]

[40 40 40  8 10 12]


In [52]:
# 3. Using start and stop parameter
# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from indices 2 to 5
numbers[2:5] = 22
print(numbers)

[ 2  4 22 22 22 12]


In [12]:
# 4. Using start, stop, and step parameter
# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify every second element from indices 1 to 5
numbers[1:5:2] = 16
print(numbers)

# Output: [ 2 16  6 16 10 12]

[ 2 16  6 16 10 12]


In [13]:
# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    # [8 10 12]

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    # [4 6 8] 

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])   # [12 8 4]
Here,

# numbers[-3:] - slices last 3 elements of numbers
# numbers[-5:-2] - slices numbers elements from 5th last to 2nd last(excluded)
# numbers[-1::-2] - slices every other numbers elements from the end with step size 2

[ 8 10 12]
[4 6 8]
[12  8  4]


In [14]:
# Reverse NumPy Array Using Negative Slicing
# In NumPy, we can also reverse array elements using the negative slicing. For example,

# import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1]
print(reversed_numbers)

# Output: [12 10 8 6 4 2]

[12 10  8  6  4  2]


2D NumPy Array Slicing
A 2D NumPy array can be thought of as a matrix, where each element has two indices, row index and column index.

To slice a 2D NumPy array, we can use the same syntax as for slicing a 1D NumPy array. The only difference is that we need to specify a slice for each dimension of the array.

Syntax of 2D NumPy Array Slicing
array[row_start:row_stop:row_step, col_start:col_stop:col_step]
Here,

row_start,row_stop,row_step - specifies starting index, stopping index, and step size for the rows respectively
col_start,col_stop,col_step - specifies starting index, stopping index, and step size for the columns respectively
Let's understand this with an example.

# create a 2D array
array1 = np.array([[1, 3, 5, 7], 
                   [9, 11, 13, 15]])

print(array1[:2, :2])

# Output

[[ 1  3]
 [ 9 11]]
Here, the , in [:2, :2] separates the rows of the array.

The first :2 returns first 2 rows i.e., entire array1. This results in

[1  3]
The second :2 returns first 2 columns from the 2 rows. This results in

[9 11]


In [15]:
import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


In [16]:
# Example: 2D NumPy Array Slicing
# import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)
Here,

# array1[:2, :2] - slices array1 that starts at the first row and first column (default values), and ends at the second row and second column (exclusive)
# array1[1:3, 2:4] - slices array1 that starts at the second row and third column (index 1 and 2), and ends at the third row and fourth column (index 2 and 3)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


- range function 
- arange function
- we can create numpy using range and arange function

In [9]:
# using range function to create numpy?
n1=np.array(range(1,10))
print(n1)

[1 2 3 4 5 6 7 8 9]


In [10]:
# using arange function to create numpy?
n1=np.arange(1,10)
print(n1)

[1 2 3 4 5 6 7 8 9]


- DIFFERENCE BETWEEN RANGE AND ARANGE FUNCTION.
- RANGE FUNCTION WILL ONLY INTEGER PARAMETER.
- ARANGE FUNCTION WILL INTEGERS AND PARAMETERS PARAMETERS.

In [11]:
np.range(1,10.5)

AttributeError: module 'numpy' has no attribute 'range'

# array initialization


In [ ]:
#to create 1-d array using ones()?
n1=np.ones(10)
print(n1)

In [ ]:
#to create 1-d array using ones()?
n1=np.ones(10,dtype=int)
print(n1)
print(n1.ndim)

In [ ]:
#to create 2 d array using ones method?
n2=np.ones((2,3),dtype=int)
print(n2)

In [ ]:
# to print identity matrix using eye()?
print(np.eye(3,dtype=int))

In [ ]:
# to print identity matrix using identity()?
np.identity(4,dtype=int)

In [ ]:
#to print the specific value?
np.full(5,7)

In [ ]:
np.full((4,4),9)

- random()
   - it is sub module in numpy.
   - using random function we can create the numpy arrays.

In [ ]:
#To genereate single random integer value
np.random.randint(10,20)

In [ ]:
# to generate the n number of random numbers?
np.random.randint(10,50,6)

In [ ]:
# to create the 2-d array using random?
np.random.randint(10,80,(2,3))

### Indexing slicing

In [ ]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n1)

In [ ]:
# to print last row
print(n1[-1])

In [ ]:
# to print column
print(n1[:,1])

In [ ]:
print(n1[2,2])

In [ ]:
print(n1[:1])
print(n1[2:])

In [ ]:
print(n1[:,0],n1[:,2])

In [ ]:
# to  print the first and last column ?
print(n1[:,[0,2]])

- Array manipulations:
- 1 1. reshape:
      - To convert the 1-d array to n-d array.
- Syntax:
   array elements==reshape(row_size*column_size)
- 2. resize:
     - Whether it is increase or decrease 
     

# To reshape the numpy array?
n1=np.array(range(10))
print(n1)

In [ ]:
#To reshape the numpy array?
n1=np.array(range(10)) 
print(n1)

In [ ]:
np.array(range(16)).reshape(4,4)

In [ ]:
np.array(range(16)).reshape(4,5)

In [ ]:
np.arange(20).reshape(4,-1)

In [ ]:
# to print the 3-d array?
# (number of sets,rows_size,column_size)
n2=np.arange(30).reshape(3,5,2)
print(n2)

In [ ]:
# resize example?
n1=np.array([[1,2,3],[4,5,6]])
print(n1)
print("--resize of array--")
print(np.resize(n1,[3,3]))

In [ ]:
# resize example?
n1=np.array([1,2,3,4,5,6])
print(n1)
print("--resize of array--")
print(np.resize(n1,[2,3]))

# stacking
- To add the new rows and columns.
- two types of stacking
- 1.vstack-will add rows
- 2.hstack- will add columns

In [ ]:
# vstack example?
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[4,4]])
print(a)
print(b)
print("apply vstack ")
print(np.vstack((a,b)))

In [ ]:
# hstack example?
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[4,4]])
print(a)
print(b)
print("apply hstack ")
print(np.hstack((a,b)))

# ravel() method
- to convert N-d array to 1-d array


In [ ]:
# using ravel() method to convert N-d array to 1-d array.
n1=np.array([[1,2,3],[4,5,6]])
print(n1)
print(n1.ravel())

In [ ]:
help(np)

In [ ]:
#numpy.org

In [ ]:
print(dir(np))

In [ ]:
# Import numpy as np and see
import numpy as np
print(np.__version__)

In [ ]:
# How to create a 1D array?
x=np.arange(10)
print(x)

In [ ]:
#  How to create a boolean array?
np.full((3,3),True,dtype=bool)

In [ ]:
np.full((9),True,dtype=bool).reshape(3,3)

In [ ]:
np.ones((3,3),dtype=bool)

In [ ]:
np.ones((9),dtype=bool).reshape(3,3)

In [ ]:
# How to extract items that satisfy a given condition from 1D array
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
arr=np.arange(10)
print(arr[arr%2==1])

In [ ]:
#How to replace items that satisfy a condition with another value in numpy array
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr=np.arange(10)
arr[arr%2==1]=-1
arr

In [ ]:
#How to replace items that satisfy a condition without affecting the original array?
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr=np.arange(10)
out=arr.copy()
out[out%2==1]=-1
print('modify array')
print(out)
print("original array")
print(arr)

In [ ]:
#How to reshape an array?
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
arr=np.arange(10)
print(arr.reshape(2,5))
print(arr.reshape(2,-1))

In [ ]:
#How to stack two arrays vertically?
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
a=np.arange(10).reshape(2,-1)
b=np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

In [ ]:
#How to stack two arrays horizontally?
# Question: Stack arrays a and b horizontally
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
a=np.arange(10).reshape(2,-1)
b=np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

In [ ]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

In [ ]:
# Question: Get the common items between a and b
# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])
# Output: array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)    

In [ ]:
#How to remove from one array those items that exist in another?
# Question: From array a remove all items present in array b
# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

In [ ]:
#How to get the positions where elements of two arrays match?
# Question: Get the positions where elements of a and b match
# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])
# Output: (array([1, 3, 5, 7]),)
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

In [5]:
#How to extract all numbers between a given range from a numpy array?
# Question: Get all items between 5 and 10 from a.
# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [6]:
#How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
# Solution
print("\nModified array")
arr[:, [1,0,2]]
'''Swapping two columns in a 2D NumPy array can be effectively done using indexing. 
Let's break down the provided code snippet step by step, particularly focusing on what happens in the line that modifies the array.

### Step-by-step Explanation

1. **Creation of the Original Array**:
   ```python
   arr = np.arange(9).reshape(3,3)
   ```
   This line creates a 1D NumPy array of numbers from 0 to 8 using `np.arange(9)`.
   Then, `reshape(3,3)` transforms it into a 2D array (matrix) with 3 rows and 3 columns.

   The output of `print(arr)` would look like this:
   ```
   Original array
   [[0 1 2]
    [3 4 5]
    [6 7 8]]
   ```

2. **Swapping Columns**:
   ```python
   arr[:, [1, 0, 2]]
   ```
   Here’s what happens in this line:
   - **`:`** refers to all rows in the array.
   - **`[1, 0, 2]`** is an index array specifying the order of columns we want to access or reorder. In this case:
     - The column at index `1` (second column) is swapped to the first position.
     - The column at index `0` (first column) is moved to the second position.
     - The column at index `2` (third column) remains in its original position.

3. **Creating the New Array**:
   When you execute `arr[:, [1, 0, 2]]`, it results in a new NumPy array with the columns reordered as specified:
   ```
   [[1 0 2]
    [4 3 5]
    [7 6 8]]
   ```
   
4. **Explanation of the Result**:
   - The first column of the original array (indices corresponding to `0, 3, 6`) is replaced by the second column (indices corresponding to `1, 4, 7`).
   - The second column (now at index `0`) takes the place of the first column.
   - The third column remains unchanged (indices corresponding to `2, 5, 8`).

### Conclusion

To actually modify `arr` in-place, you would need to assign it back like this:
```python
arr = arr[:, [1, 0, 2]]
```
This effectively swaps the columns of the array, and you can print `arr` again to see the modified result.

Using this technique leverages NumPy's powerful indexing functionalities to rearrange the data in an efficient manner without needing loops.
'''

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [7]:
 # How to swap two rows in a 2d numpy array
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
# Solution
print("\nModified array")
print(arr[[1,0,2], :])

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [3]:
#How to reverse the rows of a 2D array?
# Question: Reverse the rows of a 2D array arr.
# Input:
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
# Solution
print("\nModified array")
arr[::-1]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [2]:
#How to reverse the columns of a 2D array?
# Question: Reverse the columns of a 2D array arr.
# Input: arr = np.arange(9).reshape(3,3)
import numpy as np
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)
print("\nModified array")
arr[::-1, ::-1]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [13]:
#How to create a 2D array containing random floats between 5 and 10?
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
rand_arr=np.random.uniform(5,10,size=(5,3))
rand_arr

array([[7.21766779, 8.64435977, 6.31675596],
       [9.89087818, 8.28595906, 6.50615195],
       [5.59350267, 8.02600784, 7.70439804],
       [8.03050018, 6.44978972, 8.69385867],
       [9.77987789, 7.3349173 , 7.77699176]])